# This is a basic workflow to help you get started with Actions

name: Build and deploy from a container

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#env: 
#  AZURE_WEBAPP_NAME: HydraNewbie
#  CONTAINER_REGISTRY: ${{ secrets.REGISTRY_USERNAME }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file build/Dockerfile --tag apoursh/hydra:latest #$(date +%s)

  push: 
    runs-on: ubuntu-latest
    needs: build 
    steps: 
    - uses: actions/checkout@v2 
    - name: Push to Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: apoursh/hydra
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest"
        dockerfile: build/Dockerfile

      #  deploy: 
      #    runs-on: ubuntu-latest
      #    needs: build
      #    steps:
      #      - name: Azure authentication
      #        uses: azure/login@v1
      #        with: 
      #          creds: ${{ secrets.AZURE_CREDENTIALS }}
      #      - uses: actions/checkout@v2
      #      - name: test command 
      #        run: echo Finished build. Deploying.
